spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: dev_user
    password: dev_user
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:      ddl-auto: validate