spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      username: root 
      password: example
      database: dev
      
logging:
  level:    '[org.springframework.data.mongodb.core.MongoTemplate]': debug
      
mq:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: / 
  exchange:
    name: email_exchange
    durable: true
    autoDelete: false
  queue:
    name: email_queue
    durable: true
    exclusive: false
    autoDelete: false
  routekey: email_routekey
  
mail:
  host: localhost
  port: 1025
  username: test
  password: test