spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: dev_user
    password: dev_user
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      
mq:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: / 
  exchange:
    name: email_exchange
    durable: true
    autoDelete: false
  queue:
    name: email_queue
    durable: true
    exclusive: false
    autoDelete: false
  routekey: email_routekey
  
mail:
  host: localhost
  port: 1025
  username: test
  password: test